### PR TITLE
Initial go at tutorials/tasks/whatever

### PR DESCRIPTION
**Pull request by jnummelin**
As was [discussed](https://kontenacommunity.slack.com/archives/C1U90NQN8/p1516353687000385) at the community Slack, there is a need to have some of the common things documented as kinda short tutorials.

This PR is an attempt the put these "tutorials" in to the documentation structure and have a short "tutorial" as an example and to set the "template" for others.

I used the term tutorial, but honestly I do not like it. I'm not a fan of the term "task" either which is used in Kube docs. So I'm really open to suggestions what to call these kinda like tutorials, but shorter and more to the point type of things. :D

You can easily try how this looks like by cloning the repo, and switching to this branch. Then install `gitbook` by running `npm install gitbook-cli`. Once you have gitbook installed, run `gitbook install` and `gitbook serve`. The last command make the pages available at `localhost:4000`

For a reference, here's how the structure looks like with the "tutorials" added:
screen shot 2018-01-23 at 22 03 01

So there can be different categories of "tutorials" to group them by relevance.

Folks, WDYT?

ping @nevalla @mattip

### CODE REVIEW

**Comment by matti** [comment]
Nice! Cookbook, Lesson, Recipe, Class, Lecture, Walkthrough. I'm okay with tutorial, but maybe walkthrough could work? Kubernetes Tasks are actually like walkthroughs as it's as hard to configure something as it is to play Legend of Zelda on NES.

**Comment by nevalla** [comment]
Cool! Looking good and exactly what I was thinking too. How about "Guides"?

**Comment by kke** [comment]
How-To's?

**Comment by jnummelin** [comment]
I'm kinda torn between the terms Walkthrough and Guide.

@miskun proposed also the term Guide, so I'll go and refactor this PR to use it to see the look-and-feel for real. :)

Everyone ok with "Guide"?

**Comment by jnummelin** [comment]
What I was thinking is to add all the guide "wishes" as properly labeled issues, and let people call dips. That might work as the first simple way to organize the effort a bit.

**Comment by matti** [comment]
Guides is perfect. How-to is not bad, just a bit geeky.

**Comment by jnummelin** [comment]
To make things go forward, I'd propose we merge this to a special branch `feature/guides`. We can use that intermediary branch to collect couple of guides and then publish those.

Sounds ok for everyone?

**Comment by kke** [comment]
👍  also could perhaps utilize the GH project feature

**Comment by jnummelin** [comment]
One thumb is good enough for me :D merging to `feature/guides`

**Pull request merged**
