### PR TITLE
Guides

### PR DESCRIPTION
**Pull request by jnummelin**
This is a work-in-progress intermediary branch/PR to collect couple guides together before publishing in official docs.

## Want to contribute?

1. Fork out from `feature/guides` branch
2. Create your new guide. Follow the format of the existing ones. Add new category if needed.
2.1 Test how it looks locally: `npm install -g gitbook-cli  && gitbook serve`
3. Create PR with merge base to `feature/guides`

### CODE REVIEW

**Comment by matti** [comment]
I think you also need npm install gitbook-cli ..? maybe also with `-g`..?

and then `$ gitbook install` before the `$ gitbook serve`

**Comment by jnummelin** [comment]
> I think you also need npm install gitbook-cli ..? maybe also with -g..?

Right, wrote that out of memory without "testing" ... Fixed it.

**Comment by jnummelin** [comment]
@jakolehm WDYT, should we collect still more guides before releasing as part of the official docs?

**Comment by jakolehm** [comment]
IMHO this is enough for release.

**Comment by jnummelin** [comment]
#91 still needed to be merged, after that good to merge to master and get live

**Pull request merged**
